# Generated by Django 4.1 on 2022-09-06 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('nit_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_Empresa', models.CharField(max_length=30)),
                ('ciudad_Empresa', models.CharField(max_length=30)),
                ('direccion_Empresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('rol_id', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('rol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('usuario_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_Usu', models.CharField(max_length=50)),
                ('apellido_Usu', models.CharField(max_length=50)),
                ('correoUsu', models.CharField(max_length=60)),
                ('login', models.CharField(max_length=50)),
                ('password_Usu', models.CharField(max_length=50)),
                ('fk_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptransacciones.rol')),
            ],
        ),
        migrations.CreateModel(
            name='movimientofinanciero',
            fields=[
                ('movimiento_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion_movimiento', models.CharField(max_length=150)),
                ('tipo_movimiento', models.CharField(max_length=60)),
                ('saldo', models.IntegerField(verbose_name=20)),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptransacciones.empresa')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptransacciones.usuario')),
            ],
        ),
    ]
