# Generated by Django 4.1 on 2022-09-25 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptransacciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('cargoId', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcionCargo', models.CharField(choices=[('Admin', 'Administrador'), ('Empleado', 'Empleado')], default='Empleado', max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='movimientofinanciero',
            old_name='movimiento_id',
            new_name='movimientoId',
        ),
        migrations.RenameField(
            model_name='movimientofinanciero',
            old_name='fk_empresa',
            new_name='nit_empresa',
        ),
        migrations.RenameField(
            model_name='movimientofinanciero',
            old_name='fk_usuario',
            new_name='usuarioId',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_id',
            new_name='usuarioId',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fk_rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuemp',
            field=models.ManyToManyField(to='apptransacciones.empresa'),
        ),
        migrations.DeleteModel(
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargoId',
            field=models.ForeignKey(default=20220101, on_delete=django.db.models.deletion.CASCADE, to='apptransacciones.cargo'),
            preserve_default=False,
        ),
    ]
