# Generated by Django 4.1 on 2022-09-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptransacciones', '0003_alter_empresa_direccion_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='descripcionCargo',
            field=models.CharField(max_length=255),
        ),
    ]
