# Generated by Django 4.1 on 2022-09-25 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptransacciones', '0004_alter_cargo_descripcioncargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='isAdministrator',
            field=models.CharField(choices=[('1', 'Administrador'), ('0', 'No Administrador')], default='0', max_length=15),
        ),
        migrations.CreateModel(
            name='empresaUsuario',
            fields=[
                ('empresaUsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('nit_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptransacciones.empresa')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptransacciones.usuario')),
            ],
        ),
    ]
