# Generated by Django 4.1 on 2022-09-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptransacciones', '0005_cargo_isadministrator_empresausuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuemp',
        ),
        migrations.AddConstraint(
            model_name='empresausuario',
            constraint=models.UniqueConstraint(fields=('usuarioId', 'nit_empresa'), name='uniqueUser_Emp'),
        ),
    ]
