# Generated by Django 4.1 on 2022-09-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptransacciones', '0007_remove_movimientofinanciero_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='saldo',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], default='Ingreso', max_length=60),
        ),
    ]
