# Generated by Django 4.1 on 2022-09-26 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptransacciones', '0008_movimientofinanciero_saldo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresausuario',
            name='nit_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apptransacciones.empresa'),
        ),
        migrations.AlterField(
            model_name='empresausuario',
            name='usuarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apptransacciones.usuario'),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='nit_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apptransacciones.empresa'),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='usuarioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apptransacciones.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apptransacciones.cargo'),
        ),
    ]
